version: "3.4"

services:
  db:
    build:
      context: ./db
    env_file: .env
    shm_size: 1g
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres2
    ports:
      - "${MAPPED_POSTGRES_PORT}:5432"

  ontop:
    image: ontop/ontop-endpoint:4.2.1
    env_file: .env
    restart: unless-stopped
    environment:
      ONTOP_ONTOLOGY_FILE: /opt/ontop/input/SNOMEDCT.owl
      # Ontology below contains more meaningful disease information
      # ONTOP_ONTOLOGY_FILE: /opt/ontop/input/ado.owl
      ONTOP_XML_CATALOG_FILE: /opt/ontop/input/catalog-v001.xml
      ONTOP_MAPPING_FILE: /opt/ontop/input/SNOMEDCT.obda
      ONTOP_PROPERTIES_FILE: /opt/ontop/input/SNOMEDCT.properties
      ONTOP_PORTAL_FILE: /opt/ontop/input/SNOMEDCT.toml
      ONTOP_CORS_ALLOWED_ORIGINS: "*"
      ONTOP_DEV_MODE: "true"
    volumes:
      - ./vkg:/opt/ontop/input
      - ./jdbc:/opt/ontop/jdbc
      - ./wait-for-it:/opt/wait-for-it
    entrypoint:
      [
        "/opt/wait-for-it/wait-for-it.sh",
        "db:5432",
        "--timeout=0",
        "--strict",
        "--",
        "/opt/ontop/entrypoint.sh",
      ]
    ports:
      - "${SERVER_PORT}:8080"